### ISSUE TITLE
Issues after moving to RDS 

### ISSUE THREAD

**Issue by thaxter03** [Pizzaface/MatchU#10]
Pretty sure these were working before I moved to RDS, possible I messed up something when working in aws? Maybe one of you can try rebuilding the database

- [x] I am able to create a new user and all their information seemingly enters the DB correctly and I am successfully logged in after that. If I log out and then try to log back in I get an error.
   **_Note: I am able to log in with the users that were imported with the sql file_**
      - Create new student or teacher user
      - Log Out
      - Attempt to log back in

- [x] It looks like every user is getting assigned to a project as soon as it is created by a teacher. All I did was create a new project and now every user has a row in 'students_to_projects' for that project id
      - Create a new project as teacher
      - View the students_to_projects table and you'll see every current user assigned to that project already

    **_Note: This might actually be more of how I was thinking it would work (in a way). Every student gets assigned to all projects that are created.
    If they don't have a current group (so they aren't signed up to any projects) then they are shown a dropdown or a list of all the possible projects and they choose one. Then they sign up for a group in that project.
    Once they sign up to a group, you only show them the project in which they have a group. And user is only allowed to be in one group._**

    **_Easy to do? Worth doing? Not sure, but figured Id put it out there. Removes the need for teacher to send out codes to each individual student_**

**Comment by Pizzaface** [comment]
Problem 2 is related to the DEBUG option on line 60 of application.py. This is so I didn't have to go through and add each user to test.

**Comment by Pizzaface** [comment]
The issues with the suggestion are that then each teacher would need a unique instance of the program.

**Comment by thaxter03** [comment]
Yeah I kind of figured that would be the case. Probably not worth doing that big of a change this late. 

How will the teacher receive the nice_url for each project? Maybe if we just figure out a way to handle sending urls to students or organizing them to make it easier. 

Maybe allow the teacher to create a 'report' printout of all the projects and their respective codes so they can post that to the classroom announcements?

That would eliminate the teacher needing to send out codes to each individual
