### ISSUE TITLE
Teacher - Saving a new project

### ISSUE THREAD

**Issue by thaxter03** [Pizzaface/MatchU#7]
- Login in as Teacher -> text@example.com / password
- Create a new Project

After I hit the 'save changes' button it seems like nothing happens for a few seconds, but then it works fine.
- [x] Add a loading wheel after clicking save

The successful alert on the project page pops up after creating a new project, but never goes away unless you click 'x'.
- [x] Have alert pop up for like 2-3 seconds and fade out??

**Comment by Pizzaface** [comment]
I think this is related to #10 - after we create the project, we're adding every user as a debug.
